language: php
php:
  - '5.4'
  - '5.6'
  - '7.x'
  - hhvm # on Trusty only
  - nightly
before_install:
  -php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar self-update
before_script:
  -composer install
script: phpunit --configuration phpunit.xml --coverage-text