language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'
  - hhvm
  - nightly
before_install:
  - sudo apt-get install -y libxml2-dev
addons:
  apt:
    update: true
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

install:
  - php vendor/vendors.php 